Parameters:
  ECRRepoName:
    Type: String
    Description: Name of the ECR repository
    
Resources:

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:CreateProject
                  - codebuild:CreateWebhook
                  - codebuild:DeleteProject
                  - codebuild:DeleteWebhook
                  - codebuild:GetProject
                  - codebuild:GetProjectArtifacts
                  - codebuild:GetProjectBuildArtifacts
                  - codebuild:GetProjectBuilds
                  - codebuild:GetProjectWebhooks
                  - codebuild:ListBuildArtifactsForProject
                  - codebuild:ListBuildsForProject
                  - codebuild:ListProjects
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:UpdateProject
                Resource: "*"
        - PolicyName: AmazonS3ReadOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetObject
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyCodeBuildProject
      Description: CodeBuild project for building Docker image
      Source:
        Type: GITHUB
        Location: https://github.com/sys-2077/thumbnail-generator.git
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: us-east-1
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: $AWS_ACCOUNT_ID
          - Name: ECR_REPO_NAME
            Type: PLAINTEXT
            Value: thumbnail-project-dev-c-image-fn # Nombre del repositorio ECR
      Artifacts:
        Type: NO_ARTIFACTS

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECR_REPO_NAME

Outputs:
  CodeBuildProjectArn:
    Description: CodeBuild Project ARN
    Value: !GetAtt CodeBuildProject.Arn
  ECRRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt ECRRepository.RepositoryUri
