AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Fargate service

Parameters:
  Repository:
    Type: String
    Description: Name of the repository
  ImageTag:
    Type: String
    Description: Tag of the Docker image

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-fargate-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: arn:aws:iam::123456789012:role/ecsExecutionRole
      ContainerDefinitions:
        - Name: my-container
          Image: !Sub ${Repository}:${ImageTag}
          Essential: true
          PortMappings:
            - ContainerPort: 80

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-ecs-cluster

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: my-fargate-service
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - 'subnet-12345678'  # Replace with your subnet IDs
          SecurityGroups:
            - 'sg-abcdef01'  # Replace with your security group IDs

Outputs:
  ServiceURL:
    Description: URL of the deployed service
    Value: !GetAtt Service.LoadBalancers[0].DNSName
