AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for the Stori Challenge

Parameters:
  Repository:
    Type: String
    Description: Name of the repository
  IMAGE_TAG:
    Type: String
    Description: Tag of the Docker image

Resources:

  MyECRRepository: # 1 ECR repository for the Docker image
    Type: AWS::ECR::Repository
    Properties:
      Region: !Ref AWS_DEFAULT_REGION
      RepositoryName: !Ref ${Repository}:${IMAGE_TAG}
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true

Outputs:
  ECRRepository:
    Description: ECR Repository
    Value: !Ref MyECRRepository
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepository