name: Stori Thumbnail Images

on:
  push:
    branches:
      - main

inputs:
  _stack:
    description: 'stori-thumbnail'
    required: true
    default: 'dev'
  _repository:
    description: 'The name of the ECR repository to deploy to'
    required: true
    default: 'thumbnail-repository'
  _imageTag:
    description: 'The image tag to deploy to Fargate'
    required: true
    default: 'latest'

jobs:
  build-and-deploy:
    runs-on: python:3.8
    env:
      STACK: ${{ github.event.inputs.stack }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create ECR Stack with CloudFormation
        run: aws cloudformation create-stack \
              --stack-name $STACK-repository \
              --template-body file://ecr-stack.yaml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameters ParameterKey=Repository,ParameterValue=${{ github.event.inputs._repository }},\
                ParameterKey=ImageTag,ParameterValue=${{ github.event.inputs._imageTag }}
        working-directory: ./Infrastructure

      - name: Wait for ECR Stack to Complete with CloudFormation
        run: aws cloudformation wait stack-create-complete --stack-name $STACK-repository

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - name: Create Builder
        run: docker buildx create --use

      - name: Build & Push Docker Image
        run: docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push -t $AWS_ACCESS_KEY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$_imageTag \
              -f Dockerfile .
        working-directory: ./Docker

      - name: Describe ECR Image
        run: aws ecr describe-images \
              --region $AWS_DEFAULT_REGION \
              --repository-name $STACK-repository \
              --image-ids $AWS_ACCESS_KEY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$_imageTag
        working-directory: ./Docker