name: Stori Thumbnail Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      STACK: 'stori-thumbnail'
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPOSITORY: 'thumbnail-repository'
      IMAGE_TAG: 'latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true


