name: Build and Deploy

on:
  push:
    branches:
      - dev
jobs:
  Build:
    name: Github Actions Build
    env:
      PROJECT_NAME: aws-thumbnail-service-2
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Configure AWS credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-role
          aws-region: us-east-1
          mask-aws-account-id: true
      # Connect to ECR AWS
      - name: Connect to ECS
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com
      # Create ERC Repository 

      # 
      # PENDDING
      #

      # Create Builder
      - name: Create Builder
        run: |
          docker buildx create --use
      # Build and Push Image
      - name: Build and Push Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push -t ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/$PROJECT_NAME:latest \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg INPUT_BUCKET_NAME=${{ secrets.INPUT_BUCKET_NAME }} \
            --build-arg OUTPUT_BUCKET_NAME=${{ secrets.OUTPUT_BUCKET_NAME }} \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} -f ./Docker/Dockerfile .
      # Describe ECR Images
      - name: Describe ECR Images
        run: |
          aws ecr describe-images --repository-name $PROJECT_NAME --region ${{secrets.AWS_REGION}} --image-ids imageDigest=$(aws ecr list-images \
          --repository-name $PROJECT_NAME --region ${{secrets.AWS_REGION}} --query 'imageIds[?imageTag==`latest`]' --output json | jq -r '.[0].imageDigest')
  Components:
    name: AWS Components ECS, ECR, S3
    env:
      PROJECT_NAME: aws-thumbnail-service-2
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-role
          aws-region: us-east-1
          mask-aws-account-id: true
      - name: Input S3 Bucket
        run: aws s3 mb s3://$PROJECT_NAME-input-bucket-1

      - name: Output S3 Bucket
        run: aws s3 mb s3://$PROJECT_NAME-output-bucket-1


