name: Build and Deploy

on:
  push:
    branches:
      - dev
jobs:
  aws_cdk:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-role
          aws-region: us-east-1
          mask-aws-account-id: true
      # Connect to ECR AWS
      - name: Connect to ECS
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
      # Setup Buildx
      - name: Buildx Image
        uses: docker/setup-buildx-action@v3
      # Docker Tags
      - name: Docker Tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/aws-thumbnail-service:latest
          tags: latest
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/aws-thumbnail-service:latest
          build-args: |
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            AWS_REGION=us-east-1
          context: .
          file: ./Dockerfile

