name: Stori Thumbnail Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      STACK: 'stori-thumbnail'
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPOSITORY: 'thumbnail-repository'
      IMAGE_TAG: 'latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR Stack with CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          stack-name: $STACK-repository
          template: ./Infrastructure/erc-stack.yaml
          capabilities: CAPABILITY_NAMED_IAM
          region: $AWS_DEFAULT_REGION
          wait-until-deployed: true
          parameter-overrides: |
            RepositoryName=$REPOSITORY

      - name: Wait for ECR Stack to Complete with CloudFormation
        uses: aws-actions/aws-cloudformation-wait-for-stack@v3
        with:
          stack-name: $STACK-repository
          region: $AWS_DEFAULT_REGION

      - name: Create Builder
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: true
          tags: $AWS_ACCESS_KEY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$IMAGE_TAG
          platforms: linux/amd64,linux/arm64
          build-args: |
            AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
            AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            STACK=$STACK
            REPOSITORY=$REPOSITORY
            IMAGE_TAG=$IMAGE_TAG

      - name: Describe ECR Image
        uses: aws-actions/amazon-ecr-describe-image@v1
        with:
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$IMAGE_TAG
          
