name: Stori Thumbnail Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      STACK: 'stori-thumbnail'
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPOSITORY: 'thumbnail-repository'
      IMAGE_TAG: 'latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create ECR Stack with CloudFormation
        run: aws cloudformation create-stack --stack-name $STACK-repository --template-body file://ecr-stack.yaml --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=Repository,ParameterValue=$REPOSITORY,ParameterKey=ImageTag,ParameterValue=$IMAGE_TAG
        working-directory: ./Infrastructure

      - name: Wait for ECR Stack to Complete with CloudFormation
        run: aws cloudformation wait stack-create-complete --stack-name $STACK-repository

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - name: Create Builder
        run: docker buildx create --use

      - name: Build & Push Docker Image
        run: docker buildx build --platform linux/amd64,linux/arm64 --push -t $AWS_ACCESS_KEY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$IMAGE_TAG -f Dockerfile .
        working-directory: ./Docker

      - name: Describe ECR Image
        run: aws ecr describe-images --region $AWS_DEFAULT_REGION --repository-name $STACK-repository --image-ids $AWS_ACCESS_KEY_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$STACK-image:$IMAGE_TAG
        working-directory: ./Docker
