name: Build and Deploy

on:
  push:
    branches:
      - dev
jobs:
  aws_cdk:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-role
          aws-region: us-east-1
          mask-aws-account-id: true
      # Connect to ECR AWS
      - name: Connect to ECS
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
      - name: Create Builder
        run: |
          docker buildx create --use
      - name: Build and Push Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t 176714254348.dkr.ecr.us-east-1.amazonaws.com/aws-thumbnail-service-2:latest -f ./Docker/Dockerfile .
      - name: Describe ECR Images
        run: |
          aws ecr describe-images --repository-name aws-thumbnail-service-2 --region us-east-1 --image-ids ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/aws-service-thumbnail
